import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      <div className="h-screen w-full bg-white flex flex-col">
          <div className="h-12 w-full bg-amber-400">
              <div className="w-20 h-full  flex items-center">
                  <p className="text-3xl italic text-black font-bold">CIVILINK</p>
              </div>
          </div>
          <div className="w-full flex-1">
              {children}
          </div>

      </div>
        
      </body>
    </html>
  );
}
